### ISSUE TITLE
Update livenessProbe

### ISSUE THREAD

**Issue by Atralupus** [planetarium/9c-k8s-config#11]
Currently, the [livenessProbe](https://github.com/planetarium/k8s-config/blob/main/9c-main/configmap-probe.yaml#L6) compares the chain tip timestamp from the current timestamp. This only indirectly checks whether the tip is being updated. Therefore, we need to update the livenessProbe so that it saves the timestamp of the tip and check's if the tip has changed in the next cycle.

It doesn't necessarily have to be the timestamp, we can also use the block index for this update.

created by @area363

**Comment by area363** [comment]
Updated in https://github.com/planetarium/9c-k8s-config/pull/65/commits/385c9c551d0564ef50ea4d99a115bc3f38e7c98b.
